# .github/workflows/sbom_ingest.yml
name: SBOM Ingest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (opcional, por si luego quieres usar scripts Python)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b ./
          ./syft version

      - name: Generate SBOM for dashboard
        run: |
          mkdir -p .evidence
          # Convención de la práctica: sbom.json
          ./syft dir:. -o json > .evidence/sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-dashboard
          path: .evidence/sbom.json
